# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - release.*

pool:
  vmImage: 'windows-latest'

variables:
- group: my-var-group

- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'


